services:
  mysql:
    build: .
    container_name: learning-sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sakila-db:/docker-entrypoint-initdb.d
      - ./.my.cnf:/root/.my.cnf:ro

  adminer:
    image: adminer
    container_name: learning-sql-adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
