services:
  mysql:
    image: mysql:8.0
    container_name: learning-sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sakila-db:/docker-entrypoint-initdb.d
      - ./.my.cnf:/root/.my.cnf:ro

volumes:
  mysql-data:
